### ISSUE TITLE
header location with echo

### ISSUE THREAD

**Issue by misterfifi1** [golchha21/BoxPHPAPI#10]
Hi and thank you, 

In your get_code function : 
	echo $url = $this->authorize_url . '?' . 
	header('location: ' . $url);

the echo break the header location function. Please delete it.

**Comment by golchha21** [comment]
Thanks @misterfifi1 for highlighting the bug; made the changes and have updated the repository.

**Comment by misterfifi1** [comment]
You're welcome. 
I implemented more functions for users, group ... if you want I can share it with you. 
Last problem, I was not able to send a file the function return is "null", can you help me ?

**Comment by golchha21** [comment]
@misterfifi1 it would great if you could share the functions so that I could include it in the repository.

Also please elaborate the the problem you are facing
