### ISSUE TITLE
File Upload is not working using BOX API v2.0

### ISSUE THREAD

**Issue by rakeshnigam** [golchha21/BoxPHPAPI#14]
I tried your code and found problem in File Uploading function is not working properly.

$box->put_file($filename, $parent_id)

Also, not able to get the proper response using above function. I debug getting empty string NULL value.

it would be great help for me.

Regards,
Rakesh

**Comment by golchha21** [comment]
@rakeshnigam It's not just the file name. It should be a relative url to the file.

    // Upload file
    $box->put_file('RELATIVE FILE URL', 'FOLDER ID');

**Comment by golchha21** [comment]
@rakeshnigam 
There was some changes made in the API hence the upload was not working.
The changes have now been updated to the SDK as well.

**Comment by rakeshnigam** [comment]
Thanks !!
Should i download latest SDK from repository then try again?

**Comment by golchha21** [comment]
@rakeshnigam Yes download the latest one and then try.
