### ISSUE TITLE
File upload not working

### ISSUE THREAD

**Issue by dipakagile** [golchha21/BoxPHPAPI#20]
i try to upload file , but its not upload , i can create folder but i cant upload , its also not show any error.

$url = realpath("810268.png");
      $st = $box->put_file($url, '810268.png', '0');

**Comment by omer-sds** [comment]
yeah me also getting the same results, no file uploaded and the put_files returns null whenever i try to upload a file, any updates on this

**Comment by dipakagile** [comment]
Its Solved , Please Check Comment of committed code

**Comment by bfpnascimento** [comment]
on php 5.6 and plus, the error remains. even after change with the committed code...
any ideas?

**Comment by bfpnascimento** [comment]
well after reading the change log of PHP 5.5 to 5.6, i find the way to fix it :)

> Uploads using the @file syntax are now only supported if the CURLOPT_SAFE_UPLOAD option is set to FALSE. CURLFile should be used instead. 

on post function, just add **curl_setopt($ch, CURLOPT_SAFE_UPLOAD, false);**, on line 315.

the function must be like this:

```
private static function post($url, $params) {
			$ch = curl_init();
			curl_setopt($ch, CURLOPT_URL, $url);
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
			curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
			curl_setopt($ch, CURLOPT_SAFE_UPLOAD, false);
			curl_setopt($ch, CURLOPT_POST, true);
			curl_setopt($ch, CURLOPT_POSTFIELDS, $params);
			$data = curl_exec($ch);
			curl_close($ch);
			return $data;
		}
```

**Comment by golchha21** [comment]
The uploads is working just fine. 
Just make sure that the you provide with a **relative url**.
