### ISSUE TITLE
file upload not working

### ISSUE THREAD

**Issue by cosai** [golchha21/BoxPHPAPI#25]
thanks for the library but the parameters of the functions have no documentation. You might want to add documentation.

The thing is file upload is not working.
I have given redirect Uri as https://app.box.com/folder/0

It asks If I give grant. I say yes but on the root folder I don't see my upload.
the file got uploaded to localhost successfully but not to the box.

I checked the thread for file upload not working but didn't understand anything and because of your comment I believe it is fixed in fact.

Can you help?
Regards

Cosai

**Comment by AbdulHaye** [comment]
Same issue I've faced also

**Comment by chrisserra** [comment]
When I call this: $box->get_code(); I get the following page: 
![screen shot 2018-11-27 at 11 18 38 am](https://user-images.githubusercontent.com/5713471/49105871-8e0a5e00-f236-11e8-9170-b81cb32496a0.png)

and nothing was uploaded.

**Comment by golchha21** [comment]
The uploads is working just fine.
Just make sure that the you provide with a relative url.
