### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by JoeMc98** [golchha21/BoxPHPAPI#27]
I'm trying to call the get_code function and I am getting this error...

 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.box.com/api/oauth2/authorize?response_type=code&client_id=CLIENT_ID&redirect_uri=. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

any ideas???

**Comment by golchha21** [comment]
Please provide me with the exact code so as to look into it.
