### ISSUE TITLE
Too few arguments to function Box_API::build_url()

### ISSUE THREAD

**Issue by suhasgawde10** [golchha21/BoxPHPAPI#28]
I am trying to use this library but i am receiving following issue.

Too few arguments to function Box_API::build_url()

currently, it is accepting 3 parameters 
private function build_url($api_func, array $opts = array(), $url)
Please suggest me the value of the 1st and 2nd parameter as the example given by you consist of only one argument that is url. but it is not working

**Comment by golchha21** [comment]
Please provide me with the exact code that you are trying to use.
