### ISSUE TITLE
Security loophole: Box user's tokens are leaking publicly

### ISSUE THREAD

**Issue by iastate-zuo** [golchha21/BoxPHPAPI#31]
Currently, after the Box user logged in and authorized the folder/file access to the APP, the tokens are cached in plain text file called `token.box`, which is stored at the root of the `public` folder and hence is available to the public traffic, unless such file is deliberately shielded from the public access by setting specific access rules, which I doubt anyone would.

The problem comes from the `read_token` and `write_token` APIs, which create and/or read files without denoting a directory the `token.box` file shall store under, therefore, in the eyes of the application entry point, the default directory for the file will be the public folder where the `index.php` locates. 

A quick fix would be to define a directory location for the `token.box` file, which shall be shielded from public access by default, e.g. using the `__DIR__` variable would be sufficient in most common use cases.

**Comment by golchha21** [comment]
The tokens can be read from anywhere be it a database or a file, it's all your choosing.
As the project was created for personal use so I released it as is.
You can extend the repository in anyway you want.
