### ISSUE TITLE
put_file function

### ISSUE THREAD

**Issue by torreon129** [golchha21/BoxPHPAPI#9]
i have an issue on using your boxphpapi library(which is really great thank you so much)

i just dont know what to put in the RELATIVE FILE URL in the parameters you've shown:

	$box->put_file('RELATIVE FILE URL', '0');

please tell me thank you

**Comment by golchha21** [comment]
'RELATIVE FILE URL' is the location of the file to be uploaded.

Eg.: Suppose you have a file **[`logo.png`]** in the folder **[`images`]** which resides in the root**[`/`]**. So the relative url will be: **`'/images/logo.png'`**

And the code would be:
```$box->put_file('/images/logo.png', '0');```

**Comment by torreon129** [comment]
so if my file is in D:\Share folder and my file name is sample.txt

so the relative file url is '/Share folder/sample.txt' ??

**Comment by golchha21** [comment]
@torreon129 the url should be relative to the file from which the function is fired.
